variable "subnet_id" {
  type        = string
  description = "ID of the subnet from networking stack"
}

terraform {
  # Written for OpenTofu (tofu >= 1.6); also valid HCL for Terraform >= 1.5.
  # Single required_providers block for the whole module - OpenTofu allows
  # only one, so aws/random/local all live here.
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

# Read-only proof the Spacelift AWS integration works: queries the caller
# identity, creates nothing, costs nothing.
data "aws_caller_identity" "current" {}

output "aws_account_id" {
  value = data.aws_caller_identity.current.account_id
}

resource "random_pet" "release_name" {
  length    = 2
  separator = "-"
  keepers = {
    environment = var.environment
  }
}

resource "random_integer" "port" {
  min = 3000
  max = 3999
  keepers = {
    environment = var.environment
  }
}

resource "local_file" "release_manifest" {
  filename = "${path.module}/release-manifest.json"
  content = jsonencode({
    service     = var.service_name
    environment = var.environment
    release     = random_pet.release_name.id
    port        = random_integer.port.result
  })
}

variable "web_environments" {
  type        = list(string)
  description = "Environments to run a web server for."
  default     = ["prod", "dev", "test"]
}

variable "admin_ingress_cidr" {
  type        = string
  description = "CIDR allowed to reach the web servers over HTTP and SSH."
  # Brett's public IP as of 2026-08-19. Override with
  # TF_VAR_admin_ingress_cidr in the Spacelift environment if it changes.
  default = "164.152.178.200/32"
}

data "aws_subnet" "selected" {
  id = var.subnet_id
}

resource "aws_key_pair" "app" {
  key_name   = "orbit-labs-app"
  public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICmsrERSIAmACx6uxiePMYWsEuaMf/UbreaHE5YjVSTo orbit-labs-app"

  tags = {
    Name    = "Orbit Labs App Key"
    project = "Orbit-labs"
  }
}

resource "aws_security_group" "web" {
  name        = "orbit-labs-web-sg"
  description = "Web servers: HTTP and SSH from approved admin IP only"
  vpc_id      = data.aws_subnet.selected.vpc_id

  ingress {
    description = "HTTP from approved admin IP only (redirects to HTTPS)"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = [var.admin_ingress_cidr]
  }

  ingress {
    description = "HTTPS from approved admin IP only"
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = [var.admin_ingress_cidr]
  }

  ingress {
    description = "SSH from approved admin IP only"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.admin_ingress_cidr]
  }

  egress {
    description = "All outbound (package installs)"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name    = "Orbit Labs Web SG"
    project = "Orbit-labs"
  }
}

resource "aws_security_group" "db" {
  name        = "orbit-labs-db-sg"
  description = "MariaDB: 3306 from web servers only, SSH from admin IP"
  vpc_id      = data.aws_subnet.selected.vpc_id

  ingress {
    description     = "MariaDB from web security group only"
    from_port       = 3306
    to_port         = 3306
    protocol        = "tcp"
    security_groups = [aws_security_group.web.id]
  }

  ingress {
    description = "SSH from approved admin IP only"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.admin_ingress_cidr]
  }

  egress {
    description = "All outbound (package installs)"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name    = "Orbit Labs DB SG"
    project = "Orbit-labs"
  }
}

# AMI is PINNED (not most_recent) so instances are stable and stateful work
# (WordPress databases) survives. A most_recent lookup silently rebuilt the
# whole fleet on 2026-08-19 when Amazon published a new image, changing all
# public IPs. To move to a newer AMI, update this value deliberately and
# accept the replacement.
variable "ami_id" {
  type        = string
  description = "Pinned Amazon Linux 2023 AMI for the web fleet."
  default     = "ami-02b3d83d84b07786d"
}

# Shared WordPress DB password for prod. Generated by Terraform (not on-box)
# because two independent instances - db and web["prod"] - need the same
# secret with no coordination channel between their boot scripts. The
# `random_password` resource marks .result sensitive, so Spacelift redacts
# it from plan/apply diffs; dev and test skip this entirely by generating
# their own local password on-box, which never leaves that instance.
resource "random_password" "wp_db" {
  length  = 24
  special = false
}

resource "aws_instance" "db" {
  ami                    = var.ami_id
  instance_type          = "t3.micro"
  subnet_id              = var.subnet_id
  vpc_security_group_ids = [aws_security_group.db.id]
  key_name               = aws_key_pair.app.key_name

  user_data                   = <<-EOF
    #!/bin/bash
    dnf install -y mariadb105-server
    systemctl enable --now mariadb
    mysql <<SQL
    CREATE DATABASE IF NOT EXISTS wordpress;
    CREATE USER IF NOT EXISTS 'wpuser'@'10.0.1.%' IDENTIFIED BY '${random_password.wp_db.result}';
    GRANT ALL PRIVILEGES ON wordpress.* TO 'wpuser'@'10.0.1.%';
    FLUSH PRIVILEGES;
    SQL
  EOF
  user_data_replace_on_change = false

  tags = {
    Name    = "orbit-labs-db"
    role    = "database"
    project = "Orbit-labs"
  }
}

locals {
  # prod: WordPress talks to the dedicated MariaDB instance over the
  # private subnet (10.0.1.0/24), using the Terraform-managed shared
  # password above.
  prod_user_data = <<-EOF
    #!/bin/bash
    dnf install -y httpd php php-mysqlnd mod_ssl openssl

    cd /tmp
    curl -sO https://wordpress.org/latest.tar.gz
    tar xzf latest.tar.gz
    rm -f /var/www/html/index.html /var/www/html/index.php
    cp -rf wordpress/* /var/www/html/
    cd /var/www/html
    cp -f wp-config-sample.php wp-config.php
    sed -i "s/database_name_here/wordpress/; s/username_here/wpuser/; s#password_here#${random_password.wp_db.result}#; s/localhost/${aws_instance.db.private_ip}/" wp-config.php

    python3 - <<'PY'
    import urllib.request
    salts = urllib.request.urlopen('https://api.wordpress.org/secret-key/1.1/salt/').read().decode()
    p = '/var/www/html/wp-config.php'
    out = []
    done = False
    for l in open(p):
        if 'put your unique phrase here' in l:
            if not done:
                out.append(salts + '\n')
                done = True
            continue
        out.append(l)
    open(p, 'w').write(''.join(out))
    PY

    chown -R apache:apache /var/www/html

    TOKEN=$(curl -sX PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 300")
    PUBIP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-ipv4)
    openssl req -x509 -nodes -newkey rsa:2048 -days 365 \
      -keyout /etc/pki/tls/private/localhost.key \
      -out /etc/pki/tls/certs/localhost.crt \
      -subj "/CN=$PUBIP" -addext "subjectAltName=IP:$PUBIP"

    cat > /etc/httpd/conf.d/redirect-https.conf <<CONF
    <VirtualHost *:80>
      RewriteEngine On
      RewriteRule ^(.*)$ https://$PUBIP\$1 [R=301,L]
    </VirtualHost>
    CONF

    systemctl enable --now httpd
  EOF

  # dev/test: fully self-contained. Each installs its own local MariaDB and
  # generates its own password on-box, never shared with any other instance.
  local_user_data = <<-EOF
    #!/bin/bash
    dnf install -y httpd php php-mysqlnd mod_ssl openssl mariadb105-server
    systemctl enable --now mariadb

    DBPASS=$(openssl rand -base64 18)
    mysql <<SQL
    CREATE DATABASE IF NOT EXISTS wordpress;
    CREATE USER IF NOT EXISTS 'wpuser'@'localhost' IDENTIFIED BY '$DBPASS';
    GRANT ALL PRIVILEGES ON wordpress.* TO 'wpuser'@'localhost';
    FLUSH PRIVILEGES;
    SQL

    cd /tmp
    curl -sO https://wordpress.org/latest.tar.gz
    tar xzf latest.tar.gz
    rm -f /var/www/html/index.html /var/www/html/index.php
    cp -rf wordpress/* /var/www/html/
    cd /var/www/html
    cp -f wp-config-sample.php wp-config.php
    sed -i "s/database_name_here/wordpress/; s/username_here/wpuser/; s#password_here#$DBPASS#" wp-config.php

    python3 - <<'PY'
    import urllib.request
    salts = urllib.request.urlopen('https://api.wordpress.org/secret-key/1.1/salt/').read().decode()
    p = '/var/www/html/wp-config.php'
    out = []
    done = False
    for l in open(p):
        if 'put your unique phrase here' in l:
            if not done:
                out.append(salts + '\n')
                done = True
            continue
        out.append(l)
    open(p, 'w').write(''.join(out))
    PY

    chown -R apache:apache /var/www/html

    TOKEN=$(curl -sX PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 300")
    PUBIP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-ipv4)
    openssl req -x509 -nodes -newkey rsa:2048 -days 365 \
      -keyout /etc/pki/tls/private/localhost.key \
      -out /etc/pki/tls/certs/localhost.crt \
      -subj "/CN=$PUBIP" -addext "subjectAltName=IP:$PUBIP"

    cat > /etc/httpd/conf.d/redirect-https.conf <<CONF
    <VirtualHost *:80>
      RewriteEngine On
      RewriteRule ^(.*)$ https://$PUBIP\$1 [R=301,L]
    </VirtualHost>
    CONF

    systemctl enable --now httpd
  EOF

  web_user_data = {
    for env in var.web_environments : env => env == "prod" ? local.prod_user_data : local.local_user_data
  }
}

resource "aws_instance" "web" {
  for_each = toset(var.web_environments)

  ami                    = var.ami_id
  instance_type          = "t3.micro"
  subnet_id              = var.subnet_id
  vpc_security_group_ids = [aws_security_group.web.id]
  key_name               = aws_key_pair.app.key_name

  user_data                   = local.web_user_data[each.key]
  user_data_replace_on_change = false

  tags = {
    Name        = "orbit-labs-web-${each.key}"
    environment = each.key
    project     = "Orbit-labs"
  }
}

output "db_private_ip" {
  description = "Private IP of the MariaDB instance (VPC-internal only)"
  value       = aws_instance.db.private_ip
}

output "db_public_ip" {
  description = "Public IP of the MariaDB instance (SSH management only)"
  value       = aws_instance.db.public_ip
}

output "web_urls" {
  description = "WordPress URL per environment (HTTPS, self-signed cert)"
  value = {
    for env, inst in aws_instance.web : env => "https://${inst.public_ip}/"
  }
}

output "web_public_ips" {
  description = "Public IP per environment"
  value = {
    for env, inst in aws_instance.web : env => inst.public_ip
  }
}
